### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by EloProf** [cm0s/jquery-rcrumbs#4]
Could you added this package to bower please?

It is exactly what i need but it is a requirement for my project that i can pull it in with bower.

A short guide on how to do that can be found here:
http://bower.io/docs/creating-packages/

It should probably only take abou 10-15 minutes to do it =)

**Comment by cm0s** [comment]
Sure, I will register this plugin in bower by the end of the week.

**Comment by cm0s** [comment]
The plugin has been registred.

#bower install jquery-rcrumbs
